# Generated by Django 4.2.5 on 2024-03-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0023_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phoneno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
