# Generated by Django 4.2.5 on 2024-03-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0024_customer_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneno',
            field=models.CharField(default='8848339302', max_length=10),
        ),
    ]
