# Generated by Django 4.2.5 on 2024-03-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0026_alter_customer_phoneno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phoneno',
        ),
    ]
